# Default values for nocalhost-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

api:
  image:
    repository: codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-api
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

web:
  image:
    repository: codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-web
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations:
  dev.nocalhost: |-
    name: nocalhost-api
    serviceType: deployment
    dependLabelSelector:
      pods:
        - "app.kubernetes.io/name=mariadb"
        - "app=nocalhost-web"
    portForward:
      - 9999:9999
    containers:
      - name: nocalhost-api
        install:
          env:
            - name: FFFFF
              value: ZZZZZZ
            - name: UUUUU
              value: QQQQQ
        dev:
          gitUrl: https://github.com/nocalhost/nocalhost.git
          image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/golang:zsh
          workDir: /home/nocalhost-dev
          shell: "/bin/zsh"
          sync:
            type: send
            filePattern:
              - .
            ignoreFilePattern:
              - "./build"
          command:
            build: [ "make", "api" ]
            run: [ "make", "api", "&&", "./build/nocalhost-api", "-c", "/app/config/config.yaml" ]
            debug: [ "make", "api", "&&", "dlv", "--listen=:2345", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "./build/nocalhost-api", "--", "-c", "/app/config/config.yaml" ]
          debug:
            remoteDebugPort: 2345
          env:
            - name: NOCALHOST_INJECT_DEV_ENV
              value: WHATEVER
          portForward:
            - 8080:8080

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  port: 80

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

mariadb:
  fullnameOverride: nocalhost-mariadb
  commonAnnotations: {"helm.sh/hook":"pre-install","helm.sh/hook-weight":"1"}
  image:
    registry: codingcorp-docker.pkg.coding.net/nocalhost/public
    repository: mariadb
  auth:
    rootPassword: root
    database: nocalhost
  primary:
    persistence:
      size: "10Gi"
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
    extraVolumes:
    - name: nocalhost-api-sql-config-volume
      configMap:
        name: nocalhost-api-sql-init-config
        defaultMode: 0755
    extraVolumeMounts:
    - name: nocalhost-api-sql-config-volume
      mountPath: /docker-entrypoint-initdb.d/

#  initdbScripts:
#    my_init_script.sh: |
#      #!/bin/bash
#      echo "init database"
#      mysql -u root -p root nocalhost < /opt/init-sql/nocalhost.sql
