apiVersion: batch/v1
kind: Job
metadata:
  generateName: nocalhost-dep-installer-
  namespace: {{ .Values.namespace | default "nocalhost-reserved" }}
spec:
  template:
    spec:
      containers:
      - command:
        - /nocalhost/installer.sh
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: IfNotPresent
        name: nocalhost-dep-installer
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      restartPolicy: Never
      serviceAccount: nocalhost-dep-admin
      serviceAccountName: nocalhost-dep-admin
