apiVersion: batch/v1
kind: Job
metadata:
  name: nocalhost-dep-installer
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
      - command:
        - /nocalhost/installer.sh
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        name: nocalhost-dep-installer
        env:
          - name: DEP_NAMESPACE
            value: "{{ .Values.dep.namespace }}"
          - name: DEP_IMAGE
            value: "{{ .Values.dep.image.repository }}:{{ .Values.dep.image.tag }}"
        imagePullPolicy: Always
      restartPolicy: Never
      serviceAccountName: nocalhost-dep-installer
