---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nocalhost-dep-installer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nocalhost-dep-installer-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: nocalhost-dep-installer
    namespace: {{ .Release.Namespace }}
