configProperties:
  version: v2

application:
  name: nocalhost
  manifestType: rawManifest
  resourcePath: ["deployments/chart"]
  helmValues:
    - key: service.type
      value: ClusterIP

  services:
    - name: nocalhost-api
      serviceType: deployment
      dependLabelSelector:
        pods:
          - "app.kubernetes.io/name=mariadb"
      containers:
        - name: nocalhost-api
          dev:
            gitUrl: https://e.coding.net/codingcorp/nocalhost/nocalhost.git
            image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/golang:latest
            workDir: /home/nocalhost-dev
            shell: "bash"
            sync:
              type: send
              filePattern:
                - .
              ignoreFilePattern:
                - ".git"
            portForward:
              - 8080:8080

    - name: nocalhost-web
      serviceType: deployment
      dependLabelSelector:
        pods:
          - "app=nocalhost-api"
      containers:
        - name: nocalhost-web
          install:
            portForward:
              - 8000:80
          dev:
            gitUrl: https://e.coding.net/codingcorp/nocalhost/nocalhost-web.git
            image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/node:12.18.1-slim
            workDir: /home/nocalhost-dev
            shell: "bash"
            sync:
              type: send
              filePattern:
                - .
              ignoreFilePattern:
                - ".git"
            portForward:
              - 80:80