name: nhctl

on:
  push:
    branches: [ main, dev ]
    paths:
    - 'cmd/nhctl/**'
    - 'internal/nhctl/**'
    - 'pkg/nhctl/**'
    - '!*/**.md'
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:

  build-nhctl:
    name: Build nhctl
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make nhctl-cross

    - name: Push to Coding Artifacts
      if: ${{ github.repository == 'nocalhost/nocalhost' }}
      env:
        WINDOWS_BINARY: 'nhctl-windows-amd64.exe'
        OSX_BINARY: 'nhctl-darwin-amd64'
        LINUX_BINARY: 'nhctl-linux-amd64'
      run: |
        cd build
        curl -T ${WINDOWS_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${WINDOWS_BINARY}?version=${GITHUB_SHA}"
        curl -T ${OSX_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${OSX_BINARY}?version=${GITHUB_SHA}"
        curl -T ${LINUX_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${LINUX_BINARY}?version=${GITHUB_SHA}"

    - name: Push to Coding Artifacts
      if: ${{ github.ref == 'refs/heads/main' && github.repository == 'nocalhost/nocalhost' }}
      env:
        WINDOWS_BINARY: 'nhctl-windows-amd64.exe'
        OSX_BINARY: 'nhctl-darwin-amd64'
        LINUX_BINARY: 'nhctl-linux-amd64'
      run: |
        cd build
        curl -T ${WINDOWS_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${WINDOWS_BINARY}?version=main"
        curl -T ${OSX_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${OSX_BINARY}?version=main"
        curl -T ${LINUX_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${LINUX_BINARY}?version=main"

    - name: Push to Coding Artifacts
      if: ${{ github.ref == 'refs/heads/dev' && github.repository == 'nocalhost/nocalhost' }}
      env:
        WINDOWS_BINARY: 'nhctl-windows-amd64.exe'
        OSX_BINARY: 'nhctl-darwin-amd64'
        LINUX_BINARY: 'nhctl-linux-amd64'
      run: |
        cd build
        curl -T ${WINDOWS_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${WINDOWS_BINARY}?version=dev"
        curl -T ${OSX_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${OSX_BINARY}?version=dev"
        curl -T ${LINUX_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${LINUX_BINARY}?version=dev"

    - name: Checkout syncthing
      uses: actions/checkout@v2.3.4
      with:
        repository: nocalhost/syncthing
        path: ./syncthing-source
        ref: dev

    - name: Build syncthing
      working-directory: ./syncthing-source
      run: ./build.sh artifact all dev-version ${GITHUB_SHA}

    - name: Push to Coding Articact
      working-directory: ./syncthing-source
      env:
        VERSION: ${{ env.RELEASE_VERSION }}
      run: |
        curl -T syncthing-linux-amd64.tar.gz -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/syncthing/syncthing-linux-amd64.tar.gz?version=${GITHUB_SHA}"
        curl -T syncthing-linux-arm64.tar.gz -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/syncthing/syncthing-linux-arm64.tar.gz?version=${GITHUB_SHA}"
        curl -T syncthing-macos-amd64.zip -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/syncthing/syncthing-macos-amd64.zip?version=${GITHUB_SHA}"
        curl -T syncthing-windows-amd64.zip -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/syncthing/syncthing-windows-amd64.zip?version=${GITHUB_SHA}"
