name: nhctl

on:
  push:
    branches: [ main, dev ]
#    paths:
#    - 'cmd/nhctl/**'
#    - 'internal/nhctl/**'
#    - 'pkg/nhctl/**'
#    - '!*/**.md'
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:

  build-nhctl:
    name: Build nhctl
    runs-on: ubuntu-latest
    env:
      WINDOWS_AMD64_BINARY: 'nhctl-windows-amd64.exe'
      WINDOWS_ARM64_BINARY: 'nhctl-windows-arm64.exe'
      MACOS_AMD64_BINARY: 'nhctl-darwin-amd64'
      MACOS_ARM64_BINARY: 'nhctl-darwin-arm64'
      LINUX_AMD64_BINARY: 'nhctl-linux-amd64'
      LINUX_ARM64_BINARY: 'nhctl-linux-arm64'
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make nhctl-cross

    - name: Push to Coding Artifacts
      if: ${{ github.repository == 'nocalhost/nocalhost' }}
      run: |
        cd build
        curl -T ${WINDOWS_AMD64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${WINDOWS_AMD64_BINARY}?version=${GITHUB_SHA}"
        curl -T ${WINDOWS_ARM64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${WINDOWS_ARM64_BINARY}?version=${GITHUB_SHA}"
        curl -T ${MACOS_AMD64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${MACOS_AMD64_BINARY}?version=${GITHUB_SHA}"
        curl -T ${MACOS_ARM64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${MACOS_ARM64_BINARY}?version=${GITHUB_SHA}"
        curl -T ${LINUX_AMD64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${LINUX_AMD64_BINARY}?version=${GITHUB_SHA}"
        curl -T ${LINUX_ARM64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${LINUX_ARM64_BINARY}?version=${GITHUB_SHA}"

    - name: Push to Coding Artifacts
      if: ${{ github.ref == 'refs/heads/main' && github.repository == 'nocalhost/nocalhost' }}
      run: |
        cd build
        curl -T ${WINDOWS_AMD64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${WINDOWS_AMD64_BINARY}?version=main"
        curl -T ${WINDOWS_ARM64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${WINDOWS_ARM64_BINARY}?version=main"
        curl -T ${MACOS_AMD64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${MACOS_AMD64_BINARY}?version=main"
        curl -T ${MACOS_ARM64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${MACOS_ARM64_BINARY}?version=main"
        curl -T ${LINUX_AMD64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${LINUX_AMD64_BINARY}?version=main"
        curl -T ${LINUX_ARM64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${LINUX_ARM64_BINARY}?version=main"

    - name: Push to Coding Artifacts
      if: ${{ github.ref == 'refs/heads/dev' && github.repository == 'nocalhost/nocalhost' }}
      run: |
        cd build
        curl -T ${WINDOWS_AMD64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${WINDOWS_AMD64_BINARY}?version=dev"
        curl -T ${WINDOWS_ARM64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${WINDOWS_ARM64_BINARY}?version=dev"
        curl -T ${MACOS_AMD64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${MACOS_AMD64_BINARY}?version=dev"
        curl -T ${MACOS_ARM64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${MACOS_ARM64_BINARY}?version=dev"
        curl -T ${LINUX_AMD64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${LINUX_AMD64_BINARY}?version=dev"
        curl -T ${LINUX_ARM64_BINARY} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/${LINUX_ARM64_BINARY}?version=dev"

  build-syncthing-linux-amd64:
    name: Build syncthing amd64
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.6

      - name: Checkout syncthing
        uses: actions/checkout@v2.3.4
        with:
          repository: nocalhost/syncthing
          path: ./syncthing-source
          ref: dev

      - name: Build syncthing-amd64
        working-directory: ./syncthing-source
        run: go run build.go -targetName=syncthing -cmd=tar -nocalhostVersion=dev -nocalhostCommitId="${GITHUB_SHA}"

      - name: Push to Coding Articact
        working-directory: ./syncthing-source
        run: |
          curl -T syncthing-linux-amd64.tar.gz -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/syncthing/syncthing-linux-amd64.tar.gz?version=${GITHUB_SHA}"

  build-syncthing-macos-windows:
    name: Build syncthing macos
    runs-on: macos-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.6

      - name: Checkout syncthing
        uses: actions/checkout@v2.3.4
        with:
          repository: nocalhost/syncthing
          path: ./syncthing-source
          ref: dev

      - name: Build syncthing
        working-directory: ./syncthing-source
        run: |
          go run build.go -targetName=syncthing -cmd=zip -nocalhostVersion=dev -nocalhostCommitId="${GITHUB_SHA}"
          go run build.go -targetName=syncthing -cmd=zip -nocalhostVersion=dev -nocalhostCommitId="${GITHUB_SHA}" -goos=windows

      - name: Push to Coding Articact
        working-directory: ./syncthing-source
        run: |
          curl -T syncthing-macos-amd64.zip -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/syncthing/syncthing-macos-amd64.zip?version=${GITHUB_SHA}"
          curl -T syncthing-windows-amd64.zip -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/syncthing/syncthing-windows-amd64.zip?version=${GITHUB_SHA}"
